"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.removeStorage = exports.getStorage = exports.setStorage = exports.clearStorage = void 0;
const clearStorage = () => localStorage.clear();
exports.clearStorage = clearStorage;
const setStorage = (key, value) => localStorage.setItem(key, JSON.stringify(value));
exports.setStorage = setStorage;
const getStorage = (key) => JSON.parse(localStorage.getItem(key));
exports.getStorage = getStorage;
const removeStorage = (key) => localStorage.removeItem(key);
exports.removeStorage = removeStorage;
